import './globals.css'
import { Varela_Round } from 'next/font/google'

const varelaRound = Varela_Round({ subsets: ['latin'], weight:["400"] })

export const metadata = {
  title: 'NDM-Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </head>
      <body className={`${varelaRound.className} tracking-wider  `} >{children}</body>
    </html>
  )
}
